### ISSUE TITLE
Startup delay with sixaxis via bluetooth

### ISSUE THREAD

**Issue by MelTraX** [xboxdrv/xboxdrv#191] opened 2016-03-15 17:24 UTC
When starting xboxdrv for a PlayStation 3 controller connected via bluetooth, I have to wait one minute before the virtual joystick fires any events (so probably some sort of timeout). I start xboxdrv like this:

```
xboxdrv --evdev /dev/input/event20 --evdev-keymap KEY_#300=y,KEY_#302=a,KEY_#301=b,BTN_DEAD=x,BTN_TOP=start,BTN_TRIGGER=back,BTN_TRIGGER_HAPPY1=guide,BTN_BASE6=rb,BTN_BASE5=lb,BTN_TOP2=du,BTN_BASE2=dl,BTN_BASE=dd,BTN_PINKIE=dr,BTN_THUMB=tl,BTN_THUMB2=tr --evdev-absmap ABS_MT_TOUCH_MINOR=rt,ABS_MT_TOUCH_MAJOR=lt,ABS_X=x1,ABS_Y=y1,ABS_#2=x2,ABS_#5=y2 --mimic-xpad --axismap -Y1=Y1,-Y2=Y2 --deadzone 3000
```

Running gdb produces this backtrace while waiting:

```
#0  0x00007ffff5f26c3d in poll () from /usr/lib/libc.so.6
#1  0x00007ffff6fee235 in ?? () from /usr/lib/libusb-1.0.so.0
#2  0x00007ffff6fef1c3 in libusb_handle_events_timeout_completed () from /usr/lib/libusb-1.0.so.0
#3  0x00007ffff6fef2af in libusb_handle_events () from /usr/lib/libusb-1.0.so.0
#4  0x00000000004a1016 in USBGSource::on_source() ()
#5  0x00000000004a1035 in USBGSource::on_source_wrap(void*) ()
#6  0x00000000004a0ffd in USBGSource::on_source_dispatch(_GSource*, int (*)(void*), void*) ()
#7  0x00007ffff7247c3a in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#8  0x00007ffff7247fe0 in ?? () from /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7248302 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#10 0x000000000042809e in XboxdrvMain::run() ()
#11 0x000000000040949b in Xboxdrv::run_main(Options const&) ()
#12 0x000000000040ac24 in Xboxdrv::main(int, char**) ()
#13 0x00000000004085e7 in main ()
```

The bluetooth adapter I have is connected through USB but I don't think xboxdrv should have to call any USB related functions in this usecase.

As a workaround I made function `USBGSource::on_source_dispatch` in file `usb_gsource.cpp` always `return FALSE`. That works fine for me but I'm pretty sure that's not the solution.

I'm using Arch Linux and my last full system upgrade was on 2016-02-27. So everything is fairly recent. I did not try development versions of xboxdrv after 0.8.8 but I could if that helps.

This started happening a few months ago and it might very well be a problem in a library. But either way, I don't know why any USB stuff is being called.

**Comment by Grumbel** [comment] 2016-03-15 18:28
Duplicate of issue #144.

Yes, proper solution would be to not init the USB at all when it isn't needed.

**Closed as completed by Grumbel** 2016-03-15 18:28 UTC
